# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Default builds are on Ubuntu
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        include:
          # Also test on macOS and Windows using latest Python 3
          - os: macos-latest
            python-version: '3.x'
          - os: windows-latest
            python-version: '3.x'
    steps:
    - uses: actions/checkout@v2
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1.2
      with:
        # Skip to run brew update command on macOS.
        # See https://github.com/ts-graphviz/setup-graphviz/issues/457
        macos-skip-brew-update: 'true' # defalt false
    - name: Install Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run regression tests
      shell: bash
      run: |
        pip install .
        pip list
        pytest
